name: Android Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show files
        run: find .

      - name: Upload project files
        uses: actions/upload-artifact@v4
        with:
          name: ArizonaMobile_Project
          path: .
